### ISSUE TITLE
Perfect Amount of Commits , Also make a Repo for terminal color schemes 

### ISSUE THREAD

**Issue by Deottive** [Haruno19/Haruno19#1]
I really liked some terminal themes like the dark one or the minimal one , I hope you can provide me with these colorschemes for Alacritty or just the 8 colors

**Comment by Haruno19** [comment]
Thank you! The color scheme files are exported from iTerm2 in `.itermcolors` files and already are in the repo, but I don't know if you can import them in Alacritty, so for simplicity I'll just list the colors HEX code here:

Candy coloscheme (the one used in Minimal Green setup)
Black: 000009 454545
Red: e0af85 efa6a2
Green: 57ccaf 7fc990
Yellow: a69460 c7c873
Blue: a2b8ed ccacec
Magenta: e6a3dd f1a0c1
Cyan: 51cace 73c3e4
White: c0c0c0 ffffff

Deep Solarized colorscheme (used in the Deep Navy setup)
Black: 0e0f16 2b2d40
Red: dc322f cb4b15
Green: 859901 586e75
Yellow: b58901 657b83
Blue: 258bd2 839497
Magenta: d23682 6c71c4
Cyan: 2aa198 93a1a1
White: 999bb7 acb0d0

Here you go :)

**Comment by Deottive** [comment]
Thank you for this

**Comment by Haruno19** [comment]
No problem :)
